# 행렬과 벡터의 연산
- 행렬이나 벡터가 연산하기 위해서는 연산자와 피연산자의 shape 이 동일해야 한다

#### 행렬/벡터의 덧셈

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 5, 5, 5, 5])
x+y

array([ 6,  7,  8,  9, 10])

#### 행렬/벡터의 곱셈

In [5]:
c = 3
d = np.array([5, 10])
d*c

array([15, 30])

#### 브로드캐스팅
- 축약식의 사용

In [8]:
a = np.array([10, 11, 12])
s = 10 # 10*1벡터 : 의 축약으로 해석된다.
a - s

array([0, 1, 2])

#### 평균제거 벡터 혹은 0평균(zero-mean) 벡터
- 벡터내 원소들의 값에 평균값(mean)을 빼준 벡터  
$$x - m = \begin{bmatrix} x_1 - m \\ x_2 - m \\ \vdots \\x_N - m\end{bmatrix}$$

#### 선형조합 (linear combination)
- 벡터/행렬에 스칼라를 곱한후 더하거나 뺀것  
$$c_1x_1 + c_2x_2 + c_3x_3 + \dots + c_Lx_L = X$$  
$$c_1A_1 + c_2A_2 + c_3A_3 + \dots + c_LA_L = X$$



#### 벡터와 벡터의 곱셈
- 다양한 곱셈의 방식중 **내적(inner product)**에 관해서만 다룬다.  
  ㄴ 내적은 두 벡터를 서로 곱한 값으로 $x^Ty$ 형식으로 표기한다.  
  ㄴ 점(dot)으로 표기하는 경우도 있어 **닷 프로덕트(dot product)**라고도 한다.
     $$x \cdot y = x^T y = [x_1, x_2, \dots, x_N]\begin{bmatrix} y_1 \\ y_2 \\ \vdots \\y_N \end{bmatrix}= \Sigma$$